### ISSUE TITLE
Still possible to access Gigapan.org tiles?

### ISSUE THREAD

**Issue by bdrichards** [namrehs/OpenSeadragon.Gigapan#1]
Has there been an update to the availability of the tiles at Gigapan.com website? This plugin would be awesome except the tiles do not seem to be available. Any insight to current status of this plugin and/or access to the tiles at gigapan.org site?

**Comment by namrehs** [comment]
Thanks for letting me know about the problem. There hasn't been a change with the  Gigapan site, just the example included in this project stopped working. I think a style.css file was included in a previous openseadragon distribution, but isn't now. I've added it to this project and pointed to it in example.html. Works for me now. I even downloaded the zip of this project and the most recent openseadragon distribution to make sure. Check out the example.html file to make sure you have the required files in the correct locations relative to example.html and it should work.
I hope you find this plugin useful!
